[2016-06-01 14:31:49.100153]
ERROR
	Temporarily disabling observer LegacyLogObserverWrapper(<bound method FileLogObserver.emit of <twisted.python.log.FileLogObserver instance at 0x1066128c0>>) due to exception: [Failure instance: Traceback: <type 'exceptions.IOError'>: [Errno 32] Broken pipe
/usr/local/lib/python2.7/site-packages/twisted/internet/base.py:1090:connectionLost
/usr/local/lib/python2.7/site-packages/twisted/internet/protocol.py:90:doStop
/usr/local/lib/python2.7/site-packages/twisted/logger/_logger.py:210:info
/usr/local/lib/python2.7/site-packages/twisted/logger/_logger.py:132:emit
--- <exception caught here> ---
/usr/local/lib/python2.7/site-packages/twisted/logger/_observer.py:131:__call__
/usr/local/lib/python2.7/site-packages/twisted/logger/_legacy.py:93:__call__
/usr/local/lib/python2.7/site-packages/twisted/python/log.py:557:emit
/usr/local/lib/python2.7/site-packages/twisted/python/util.py:715:untilConcludes
]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1090, in connectionLost
    self.factory.doStop()
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/protocol.py", line 90, in doStop
    factory=self)
  File "/usr/local/lib/python2.7/site-packages/twisted/logger/_logger.py", line 210, in info
    self.emit(LogLevel.info, format, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/twisted/logger/_logger.py", line 132, in emit
    self.observer(event)
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/site-packages/twisted/logger/_observer.py", line 131, in __call__
    observer(event)
  File "/usr/local/lib/python2.7/site-packages/twisted/logger/_legacy.py", line 93, in __call__
    self.legacyObserver(event)
  File "/usr/local/lib/python2.7/site-packages/twisted/python/log.py", line 557, in emit
    util.untilConcludes(self.write, timeStr + " " + msgStr)
  File "/usr/local/lib/python2.7/site-packages/twisted/python/util.py", line 715, in untilConcludes
    return f(*a, **kw)
exceptions.IOError: [Errno 32] Broken pipe

[2016-06-01 14:31:52.567905]
ERROR
	Temporarily disabling observer LegacyLogObserverWrapper(<bound method FileLogObserver.emit of <twisted.python.log.FileLogObserver instance at 0x1066128c0>>) due to exception: [Failure instance: Traceback: <type 'exceptions.IOError'>: [Errno 32] Broken pipe
/usr/local/lib/python2.7/site-packages/twisted/internet/base.py:1090:connectionLost
/usr/local/lib/python2.7/site-packages/twisted/internet/protocol.py:90:doStop
/usr/local/lib/python2.7/site-packages/twisted/logger/_logger.py:210:info
/usr/local/lib/python2.7/site-packages/twisted/logger/_logger.py:132:emit
--- <exception caught here> ---
/usr/local/lib/python2.7/site-packages/twisted/logger/_observer.py:131:__call__
/usr/local/lib/python2.7/site-packages/twisted/logger/_legacy.py:93:__call__
/usr/local/lib/python2.7/site-packages/twisted/python/log.py:557:emit
/usr/local/lib/python2.7/site-packages/twisted/python/util.py:715:untilConcludes
]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1090, in connectionLost
    self.factory.doStop()
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/protocol.py", line 90, in doStop
    factory=self)
  File "/usr/local/lib/python2.7/site-packages/twisted/logger/_logger.py", line 210, in info
    self.emit(LogLevel.info, format, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/twisted/logger/_logger.py", line 132, in emit
    self.observer(event)
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/site-packages/twisted/logger/_observer.py", line 131, in __call__
    observer(event)
  File "/usr/local/lib/python2.7/site-packages/twisted/logger/_legacy.py", line 93, in __call__
    self.legacyObserver(event)
  File "/usr/local/lib/python2.7/site-packages/twisted/python/log.py", line 557, in emit
    util.untilConcludes(self.write, timeStr + " " + msgStr)
  File "/usr/local/lib/python2.7/site-packages/twisted/python/util.py", line 715, in untilConcludes
    return f(*a, **kw)
exceptions.IOError: [Errno 32] Broken pipe

[2016-06-01 14:31:57.143353]
ERROR
	Temporarily disabling observer LegacyLogObserverWrapper(<bound method FileLogObserver.emit of <twisted.python.log.FileLogObserver instance at 0x1066128c0>>) due to exception: [Failure instance: Traceback: <type 'exceptions.IOError'>: [Errno 32] Broken pipe
/usr/local/lib/python2.7/site-packages/twisted/internet/base.py:615:sigTerm
/usr/local/lib/python2.7/site-packages/twisted/python/threadable.py:53:sync
/usr/local/lib/python2.7/site-packages/twisted/python/log.py:282:msg
/usr/local/lib/python2.7/site-packages/twisted/logger/_legacy.py:154:publishToNewObserver
--- <exception caught here> ---
/usr/local/lib/python2.7/site-packages/twisted/logger/_observer.py:131:__call__
/usr/local/lib/python2.7/site-packages/twisted/logger/_legacy.py:93:__call__
/usr/local/lib/python2.7/site-packages/twisted/python/log.py:557:emit
/usr/local/lib/python2.7/site-packages/twisted/python/util.py:715:untilConcludes
]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/base.py", line 615, in sigTerm
    log.msg("Received SIGTERM, shutting down.")
  File "/usr/local/lib/python2.7/site-packages/twisted/python/threadable.py", line 53, in sync
    return function(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/twisted/python/log.py", line 282, in msg
    _publishNew(self._publishPublisher, actualEventDict, textFromEventDict)
  File "/usr/local/lib/python2.7/site-packages/twisted/logger/_legacy.py", line 154, in publishToNewObserver
    observer(eventDict)
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/site-packages/twisted/logger/_observer.py", line 131, in __call__
    observer(event)
  File "/usr/local/lib/python2.7/site-packages/twisted/logger/_legacy.py", line 93, in __call__
    self.legacyObserver(event)
  File "/usr/local/lib/python2.7/site-packages/twisted/python/log.py", line 557, in emit
    util.untilConcludes(self.write, timeStr + " " + msgStr)
  File "/usr/local/lib/python2.7/site-packages/twisted/python/util.py", line 715, in untilConcludes
    return f(*a, **kw)
exceptions.IOError: [Errno 32] Broken pipe

[2016-06-01 14:31:57.144172]
ERROR
	Temporarily disabling observer LegacyLogObserverWrapper(<bound method FileLogObserver.emit of <twisted.python.log.FileLogObserver instance at 0x1066128c0>>) due to exception: [Failure instance: Traceback: <type 'exceptions.IOError'>: [Errno 32] Broken pipe
/usr/local/lib/python2.7/site-packages/twisted/internet/tcp.py:1108:_logConnectionLostMsg
/usr/local/lib/python2.7/site-packages/twisted/python/threadable.py:53:sync
/usr/local/lib/python2.7/site-packages/twisted/python/log.py:282:msg
/usr/local/lib/python2.7/site-packages/twisted/logger/_legacy.py:154:publishToNewObserver
--- <exception caught here> ---
/usr/local/lib/python2.7/site-packages/twisted/logger/_observer.py:131:__call__
/usr/local/lib/python2.7/site-packages/twisted/logger/_legacy.py:93:__call__
/usr/local/lib/python2.7/site-packages/twisted/python/log.py:557:emit
/usr/local/lib/python2.7/site-packages/twisted/python/util.py:715:untilConcludes
]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 1108, in _logConnectionLostMsg
    log.msg('(%s Port %s Closed)' % (self._type, self._realPortNumber))
  File "/usr/local/lib/python2.7/site-packages/twisted/python/threadable.py", line 53, in sync
    return function(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/twisted/python/log.py", line 282, in msg
    _publishNew(self._publishPublisher, actualEventDict, textFromEventDict)
  File "/usr/local/lib/python2.7/site-packages/twisted/logger/_legacy.py", line 154, in publishToNewObserver
    observer(eventDict)
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/site-packages/twisted/logger/_observer.py", line 131, in __call__
    observer(event)
  File "/usr/local/lib/python2.7/site-packages/twisted/logger/_legacy.py", line 93, in __call__
    self.legacyObserver(event)
  File "/usr/local/lib/python2.7/site-packages/twisted/python/log.py", line 557, in emit
    util.untilConcludes(self.write, timeStr + " " + msgStr)
  File "/usr/local/lib/python2.7/site-packages/twisted/python/util.py", line 715, in untilConcludes
    return f(*a, **kw)
exceptions.IOError: [Errno 32] Broken pipe

[2016-06-01 14:31:57.144651]
ERROR
	Temporarily disabling observer LegacyLogObserverWrapper(<bound method FileLogObserver.emit of <twisted.python.log.FileLogObserver instance at 0x1066128c0>>) due to exception: [Failure instance: Traceback: <type 'exceptions.IOError'>: [Errno 32] Broken pipe
/usr/local/lib/python2.7/site-packages/twisted/internet/tcp.py:1125:connectionLost
/usr/local/lib/python2.7/site-packages/twisted/internet/protocol.py:90:doStop
/usr/local/lib/python2.7/site-packages/twisted/logger/_logger.py:210:info
/usr/local/lib/python2.7/site-packages/twisted/logger/_logger.py:132:emit
--- <exception caught here> ---
/usr/local/lib/python2.7/site-packages/twisted/logger/_observer.py:131:__call__
/usr/local/lib/python2.7/site-packages/twisted/logger/_legacy.py:93:__call__
/usr/local/lib/python2.7/site-packages/twisted/python/log.py:557:emit
/usr/local/lib/python2.7/site-packages/twisted/python/util.py:715:untilConcludes
]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 1125, in connectionLost
    self.factory.doStop()
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/protocol.py", line 90, in doStop
    factory=self)
  File "/usr/local/lib/python2.7/site-packages/twisted/logger/_logger.py", line 210, in info
    self.emit(LogLevel.info, format, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/twisted/logger/_logger.py", line 132, in emit
    self.observer(event)
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/site-packages/twisted/logger/_observer.py", line 131, in __call__
    observer(event)
  File "/usr/local/lib/python2.7/site-packages/twisted/logger/_legacy.py", line 93, in __call__
    self.legacyObserver(event)
  File "/usr/local/lib/python2.7/site-packages/twisted/python/log.py", line 557, in emit
    util.untilConcludes(self.write, timeStr + " " + msgStr)
  File "/usr/local/lib/python2.7/site-packages/twisted/python/util.py", line 715, in untilConcludes
    return f(*a, **kw)
exceptions.IOError: [Errno 32] Broken pipe

[2016-06-01 14:31:57.145316]
ERROR
	Temporarily disabling observer LegacyLogObserverWrapper(<bound method FileLogObserver.emit of <twisted.python.log.FileLogObserver instance at 0x1066128c0>>) due to exception: [Failure instance: Traceback: <type 'exceptions.IOError'>: [Errno 32] Broken pipe
/usr/local/lib/python2.7/site-packages/twisted/internet/base.py:1211:mainLoop
/usr/local/lib/python2.7/site-packages/twisted/python/threadable.py:53:sync
/usr/local/lib/python2.7/site-packages/twisted/python/log.py:282:msg
/usr/local/lib/python2.7/site-packages/twisted/logger/_legacy.py:154:publishToNewObserver
--- <exception caught here> ---
/usr/local/lib/python2.7/site-packages/twisted/logger/_observer.py:131:__call__
/usr/local/lib/python2.7/site-packages/twisted/logger/_legacy.py:93:__call__
/usr/local/lib/python2.7/site-packages/twisted/python/log.py:557:emit
/usr/local/lib/python2.7/site-packages/twisted/python/util.py:715:untilConcludes
]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1211, in mainLoop
    log.msg('Main loop terminated.')
  File "/usr/local/lib/python2.7/site-packages/twisted/python/threadable.py", line 53, in sync
    return function(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/twisted/python/log.py", line 282, in msg
    _publishNew(self._publishPublisher, actualEventDict, textFromEventDict)
  File "/usr/local/lib/python2.7/site-packages/twisted/logger/_legacy.py", line 154, in publishToNewObserver
    observer(eventDict)
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/site-packages/twisted/logger/_observer.py", line 131, in __call__
    observer(event)
  File "/usr/local/lib/python2.7/site-packages/twisted/logger/_legacy.py", line 93, in __call__
    self.legacyObserver(event)
  File "/usr/local/lib/python2.7/site-packages/twisted/python/log.py", line 557, in emit
    util.untilConcludes(self.write, timeStr + " " + msgStr)
  File "/usr/local/lib/python2.7/site-packages/twisted/python/util.py", line 715, in untilConcludes
    return f(*a, **kw)
exceptions.IOError: [Errno 32] Broken pipe

